# Extra tip:
# Comments in Makefiles start with '#' and stretch
# to the end of the line!

# Start writing below this line...
example: example.c
	gcc example.c -o example

.PHONY: clean

clean:
	rm example