# Extra tip:
# Comments in Makefiles start with '#' and stretch
# to the end of the line!

# Start writing below this line...

example: example.c
	gcc -o example example.c

.PHONY: clean

clean:
	rm example